{
    "docs": "https://docs.ansible.com/ansible-core/2.18/dev_guide/testing/sanity/pylint.html", 
    "results": [
        {
            "message": "The test `ansible-test sanity --test pylint` [[explain](https://docs.ansible.com/ansible-core/2.18/dev_guide/testing/sanity/pylint.html)] failed with 9 errors:", 
            "output": "plugins/filter/generalized_time_to_epoch.py:64:0: trailing-newlines: Trailing newlines\nplugins/module_utils/dsldap.py:235:0: trailing-newlines: Trailing newlines\nplugins/modules/ds_repl_binddn_auth.py:139:0: trailing-newlines: Trailing newlines\nplugins/modules/ds_repl_enable.py:81:9: subprocess-run-check: 'subprocess.run' used without explicitly defining the value for 'check'.\nplugins/modules/ds_repl_enable.py:166:0: trailing-newlines: Trailing newlines\nplugins/modules/ds_repl_init.py:80:11: subprocess-run-check: 'subprocess.run' used without explicitly defining the value for 'check'.\nplugins/modules/ds_repl_init.py:150:0: trailing-newlines: Trailing newlines\nplugins/modules/ds_repl_manager.py:59:13: subprocess-run-check: 'subprocess.run' used without explicitly defining the value for 'check'.\nplugins/modules/ds_repl_manager.py:144:0: trailing-newlines: Trailing newlines"
        }
    ], 
    "verified": false
}
